# first_name = driver.find_element(By.NAME,'name')
# first_name.send_keys("Krishna kumar")
# email = driver.find_element(By.NAME,'email')
# email.send_keys("krishnasav44@gmail.com")
# username = driver.find_element(By.ID,'username')
# username.send_keys("krishna44")
# password = driver.find_element(By.ID,'password')
# password.send_keys("Krishna@4044")
# conform_password = driver.find_element(By.ID,'password_confirm')
# conform_password.send_keys("Krishna@4044")
# dropdown_element = driver.find_element(By.ID, 'country')
# select = Select(dropdown_element)
# select.select_by_visible_text('Somalia')
# # checkbox_input = driver.find_element(By.XPATH, "//input[@value ='sitewide research']")
# # checkbox_input.click()
# submit_button = driver.find_element(By.XPATH, "//input[@value ='Register']")
# submit_button.click()